config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end

  root 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
# task controller
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:create]
  def create
    @task = @project.tasks.create(task_params)

    redirect_to @project
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @project, notice: 'Task was completed'
  end

  def destroy
    if @task.destroy
      flash[:success] = 'Task deleted'
    else
      flash[:error] = 'The task couldn\'t be deleted'
    end
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoAppTwo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

</head>
<body class="container">

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2 form-control-label">
      <%= f.label :description %>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-12">
      <%= f.submit class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<%= link_to 'New Project', new_project_path %>


<div class="card-deck-wrapper">
  <div class="card-deck">
  <% @projects.each do |project| %>
    <div class="card">
      <img src="" alt="">
      <div class="card-block">
        <h4 class="card-title"><%= project.title %></h4>
        <p class="card-text"><%= project.description %></p>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= link_to 'Show', project %></li>
          <li class="list-group-item"><%= link_to 'Edit', edit_project_path(project) %></li>
          <li class="list-group-item"><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<section>
  <%= render @project.tasks %>
  <%= render "tasks/form" %>
</section>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for([@project, @project.tasks.build]) do |f| %>
  <%= f.text_field :content, placeholder: 'New Task' %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<% if task.completed? %>
<div style="opacity: 0.2">
  <p>
  <strike><%= task.content %></strike>
  </p>
  <%= link_to "Delete", project_task_path(@project,task.id), method: :delete, data: {confirm: "Are you sure?"} %>
</div>
<% else %>
<p>
  <%= task.content %>
</p>
<div>
  <%= link_to "Delete", project_task_path(@project,task.id), method: :delete, data: {confirm: "Are you sure?"} %>
  <%= link_to "Mark as Completed", complete_project_task_path(@project,task.id), method: :patch %>
</div>
<% end %>